Use uintptr to track methods instances instead of *C.sqlite3
This should make cgo happier, and not fail with panics like:

runtime: pointer 0xa544345 to unused region of span span.base()=0x9db0000 span.limit=0x9db1f80 span.state=1
fatal error: found bad pointer in Go heap (incorrect use of unsafe or cgo?)